---
- name: Hello World! 
  hosts: all

  tasks:

  - name: Hello World! {{ my_variable }}
    shell: echo "Hi! Tower is working! v2 My variable':' '{{ my_variable }}'"

  - name: Creates directory
    file:
      path: /tmp/MyTest
      state: directory
      
      
  - name: Encription status...
    debug: msg="I created this debug message '{{ my_variable }}'"
